create table QUOCGIA(
MAQG VARCHAR(5) PRIMARY KEY,
TENQG NVARCHAR(50) NOT NULL
)

CREATE TABLE HUANLUYENVIEN(
MAHLV VARCHAR (5) PRIMARY KEY,
TENHLV NVARCHAR(100)NOT NULL,
NGAYSINH DATETIME,
DIACHI NVARCHAR(50),
DIEMTHOAI VARCHAR(20),
MAQG VARCHAR(5) NOT NULL,

FOREIGN KEY(MAQG) REFERENCES QUOCGIA(MAQG)
)

DROP TABLE QUOCGIA;

CREATE TABLE CAUTHU(
MACT NUMERIC IDENTITY(1,1) PRIMARY KEY,
HOTEN NVARCHAR(100) NOT NULL,
VITRI NVARCHAR(20) NOT NULL ,
NGAYSINH DATETIME,
DIACHI NVARCHAR(200),
MACLB VARCHAR(5) NOT NULL,
MAQG VARCHAR(5) NOT NULL,
SO INT NOT NULL
)

CREATE TABLE CAULACBO(
MACLB VARCHAR(5) PRIMARY KEY,
TENCLB NVARCHAR(100) NOT NULL,
MASAN VARCHAR(5) NOT NULL,
MATINH VARCHAR(5) NOT NULL,
)

CREATE TABLE TINH(
MATINH VARCHAR(5) PRIMARY KEY,
TENTINH NVARCHAR(100) NOT NULL,
)

CREATE TABLE SANVD(
MASAN VARCHAR(5) PRIMARY KEY,
TENSAN NVARCHAR(100) NOT NULL,
DIACHI NVARCHAR(200),
)

CREATE TABLE HLV_CLB(
MAHLV VARCHAR(5),
MACLB VARCHAR(5),
PRIMARY KEY (MAHLV, MACLB),
VAITRO NVARCHAR(100) NOT NULL,
)

CREATE TABLE TRANDAU(
MATRAN NUMERIC IDENTITY(1,1) PRIMARY KEY,
NAM INT NOT NULL,
VONG INT NOT NULL,
NGAYTD DATETIME,
MACLB1 VARCHAR(5) NOT NULL,
MACLB2 VARCHAR(5) NOT NULL,
MASAN VARCHAR(5) NOT NULL,
KETQUA VARCHAR(5) NOT NULL,
)

CREATE TABLE BANGXH(
MACLB VARCHAR(5),
NAM INT, 
VONG INT,
PRIMARY KEY( MACLB, NAM, VONG), 
SOTRAN INT NOT NULL,
THANG INT NOT NULL,
HOA INT NOT NULL,
THUA INT NOT NULL,
HIEUSO VARCHAR(5) NOT NULL,
DIEM INT NOT NULL,
HANG INT NOT NULL,
)

-- CÂU 3
-- A
--Cho biết thông tin (mã cầu thủ, họ tên, số áo, vị trí, ngày sinh, địa chỉ) của tất cả các cầu thủ

SELECT * FROM CAUTHU

--Hiển thị thông tin tất cả các cầu thủ có số áo là 7 chơi ở vị trí Tiền vệ
SELECT * FROM CAUTHU
WHERE SO = 7
AND VITRI = N'Tiền Vệ';

--Cho biết tên, ngày sinh, địa chỉ, điện thoại của tất cả các huấn luyện viên
SELECT * FROM HUANLUYENVIEN;

--Hiển thi thông tin tất cả các cầu thủ có quốc tịch Việt Nam thuộc câu lạc bộ Becamex Bình Dương.
SELECT * FROM CAUTHU
WHERE MAQG = 'VN' AND MACLB = 'BBD';

--Cho biết mã số, họ tên, ngày sinh, địa chỉ và vị trí của các cầu thủ thuộc đội bóng SHB Đà Nẵng’ có quốc tịch VN
SELECT FROM CAUTHU(MACT, HOTEN, VITRI, NGAYSINH, DIACHI)


